### ISSUE TITLE
Issue facing while Adding extra columns in existing table.

### ISSUE THREAD

**Issue by lekshmisk** [beingnin/xAudit#15]
I am getting one error while adding columns in existing table. its not updating in the replica table. I will share you some screen shot for the same.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/102799995/161245949-7abce2a8-b870-4c8c-9a1d-8a153eb62d28.png)

**Comment by beingnin** [comment]
It seems like the issue is when force merging a schema change is occurring for a column addition/removal.

Force merge should be used when modifying a column(changing data type)

**Comment by lekshmisk** [comment]
I updated with latest version but again i am getting Error
![image](https://user-images.githubusercontent.com/102799995/161474446-7c7964cf-a19a-4edc-9fb9-a17be54194b2.png)
